name: elara
description: "A new Flutter project."
 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.8.1
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Networking
  dio: ^5.4.0

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.3.2

  # Local Storage
  shared_preferences: ^2.2.2
  
   # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1
  
  # Charts
  fl_chart: ^0.68.0
   

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0
 
flutter:
 
  uses-material-design: true

  assets:
    - assets/logo/
  fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 700
  